{
 "title": "MQTTDevice",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MQTTDevice",
   "type": "graph",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "Temperatur" }
   ],
   "targets": [
    {
     "alias": "Temperatur Maische-Sud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT mean(\"Temperatur\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '1') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Zieltemperatur Maische-Sud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "select": [
      [
       { "params": [ "TargetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Powerlevel Maische-Sud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT mean(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Temperatur Nachguss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Zieltemperatur Nachguss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "select": [
      [
       { "params": [ "TargetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Powerlevel Nachguss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Powerlevel RHE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT mean(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Aktuelle Temperaturen",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "Maische-Sud",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"Temperatur\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '1')",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"Temperatur\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2') ",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"Temperatur\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2') ",
     "select": [
      [
       { "params": [ "Temperatur" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Zieltemperaturen",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "alias": "Maische-Sud",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"TargetTemp\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2')",
     "select": [
      [
       { "params": [ "TargetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"TargetTemp\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2')",
     "select": [
      [
       { "params": [ "TargetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "RHE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"TargetTemp\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2')",
     "select": [
      [
       { "params": [ "TargetTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Powerlevel",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "alias": "Maische-Sud",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '1') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "query": "SELECT last(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2') ",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "RHE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqttdevice_status",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ID", "operator": "=", "value": "3" }
     ]
    }
   ]
  }
 ]
}